name: metaneusseq-domedenseseq_meta-${dataset.scene}
tag: ''
seed: 42

defaults:
  - ../../base.yaml

dataset:
  name: domedenserawseq_meta
  subject: Subject0002
  frames: [1000, 1300, 1600, 1900, 2200, 2500, 2800, 3100, 3400, 3700, 4000, 4300, 4600, 4900, 5200, 5500, 5800, 6100,
           6400, 6700, 7000, 7300, 7600, 7900, 8200, 8500, 8800, 9100, 9400, 9700, 10000, 10300, 10600, 10900, 11200,
           11500, 11800, 12100, 12400, 12700, 13000, 13300, 13600, 13900, 14200, 14500, 14800, 15100, 15400, 15700,
           16000, 16300, 16600, 16900, 17200, 17500, 17800, 18100, 18400, 18700, 19000, 19300, 19600, 19900, 20200,
           20500, 20800, 21100, 21400, 21700, 22000, 22300, 22600, 22900, 23200, 23500, 23800, 24100, 24400, 24700,
           25000, 25300, 25600, 25900, 26200, 26500, 26800, 27100, 27400, 27700, 28000, 28300, 28600, 28900, 29200,
           29500, 29800, 30100, 30400, 30700, 31000, 31300, 31600, 31900, 32200, 32500, 32800, 33100]
  frames_path:

  data_dir: ${root_dir}/datas/${dataset.subject}/tight/training
  scene: ${dataset.subject}
  img_downscale: 1 # specify training image size by either img_wh or img_downscale
  camera_scale: 1000.0
  near_plane: 2.0
  far_plane: 6.0
  train_split: 'train'
  val_split: 'val'
  test_split: 'test'
  deformer: 'ddc' #‘smpl'
  cano_motion: 'template' # 'world'
  default_path: ${root_dir}/datas/ddc_configs/default.yaml
  config_path: ${root_dir}/datas/ddc_configs/s2_smooth_eg.yaml
  active_camera: [ 0, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 27, 28, 30,
                   31, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 46, 48, 49, 51, 52, 53, 54, 55, 56, 57, 59,
                   61, 62, 63, 64, 65, 67, 68, 69, 70, 72, 73, 74, 75, 76, 79, 81, 83, 84, 85, 87, 88, 90,
                   91, 92, 93, 94, 95, 96, 98, 99, 100, 101, 104, 105, 106, 108, 110, 112, 114, 115 ]
  active_camera_all: False
  smooth: True
  smoothDQ: False
  subdiv: 0
  loose: False
  inner_steps: 24
  blur: False
  blurNum: 1
  threshold_smpl: 0.075
  threshold_ddc: 0.05
  smpl_name: "smpl_params_smplx.npz"
  smpl_gender: 'neutral'
  ddc_name: "ddc_all_smooth_less_new.npz"
  with_depth: False
  depth_shift: 0.0
  threshold_rigid: 0.05
  threshold_outer: 0.05
  preload: True
  occlusion_template_dir:
model:
  decay_step: 300
  grid_resolution: 256
  name: neus
  radius: 1.25
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 20000
  learned_background: false
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    grad_type: analytic
    isosurface:
      method: mc
      resolution: [256,512,256]
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels:  12 #14
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: false
  texture:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: Identity
      scale: 1.0
      offset: 0.0
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
system:
  name: metaneusseq-system
  loss:
    lambda_rgb_huber: 10.0
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 0.
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_sparsity: 0.01
    lambda_distortion: 0.
    lambda_opaque: 0.
    sparsity_scale: 1.
    lambda_sdf_reg: 0

  outer_optimizer:
    name: SGD
    args:
      lr: 1.0

  inner_optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [ 0.9, 0.99 ]
      eps: 1.e-15
#    params:
#      geometry:
#          lr: 0.01
#      texture:
#          lr: 0.01
#      variance:
##          lr: 0.001

  warmup_steps: 100
  warmup_steps_inner: 50
#  scheduler:
#    name: SequentialLR
#    interval: step
#    milestones:
#      - ${system.warmup_steps}
  scheduler:
    name: LinearLR # linear warm-up in the first system.warmup_steps steps
    interval: step
    args:
      start_factor: 1.0 #0.01 #0.0001 -> 0.1
      end_factor: 1.0
      total_iters: ${system.warmup_steps}
#      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
#        args:
#          start_factor: 1.0 #0.01 #0.0001 -> 0.1
#          end_factor: 1.0
#          total_iters: ${system.warmup_steps}
#      - name: ExponentialLR
#        args:
#          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.warmup_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: 200

export:
  save_mesh: false
  chunk_size: 2097152
  export_vertex_color: True

trainer:
  max_steps: 3000
  log_every_n_steps: 10
  num_sanity_val_steps: 0
  val_check_interval: 20
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 32