name: metaneusseq-domedenseseq_meta-${dataset.scene}
tag: ''
seed: 42

defaults:
  - ../../base.yaml

dataset:
  name: domedenserawseq_meta
  subject: Subject0003
  frames: [1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400, 3600, 3800, 4000, 4200, 4400, 4600, 4800, 5000, 5200, 5400, 5600, 5800, 6000, 6200, 6400, 6600, 6800, 7000, 7200, 7400, 7600, 7800, 8000, 8200, 8400, 8600, 8800, 9000, 9200, 9400, 9600, 9800, 10000, 10200, 10400, 10600, 10800, 11000, 11200, 11400, 11600, 11800, 12000, 12200, 12400, 12600, 12800, 13000, 13200, 13400, 13600, 13800, 14000, 14200, 14400, 14600, 14800, 15000, 15200, 15400, 15600, 15800, 16000, 16200, 16400, 16600, 16800, 17000, 17200, 17400, 17600, 17800, 18000, 18200, 18400, 18600, 18800]


  frames_path:
  data_dir: ${root_dir}/datas/${dataset.subject}/tight/training
  scene: ${dataset.subject}
  img_downscale: 1 # specify training image size by either img_wh or img_downscale
  near_plane: 2.0
  far_plane: 6.0
  train_split: 'train'
  val_split: 'val'
  test_split: 'test'
  deformer: 'ddc'
  cano_motion: 'template' # 'world'
  default_path: ${root_dir}/datas/ddc_configs/default.yaml
  config_path: ${root_dir}/datas/ddc_configs/s3_smooth_eg.yaml
  active_camera: []
  active_camera_all: True
  smooth: True
  smoothDQ: False
  subdiv: 0
  loose: True
  inner_steps: 24
  blur: False
  blurNum: 1
  threshold_smpl: 0.075
  threshold_ddc: 0.05
  smpl_name: "smpl_params_smplx.npz"
  smpl_gender: 'neutral'
  ddc_name: "ddc_all_smooth_less.npz"
  with_depth: False
  depth_shift: 0.0
  threshold_rigid: 0.05
  threshold_outer: 0.01
  preload: True
model:
  decay_step: 300
  grid_resolution: 256
  name: neus
  radius: 1.25
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 20000
  learned_background: false
  background_color: random
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: ${model.radius}
    feature_dim: 13
    grad_type: analytic
    isosurface:
      method: mc
      resolution: [256,512,256]
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels:  12 #14
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: false

  texture:
    name: volume-radiance
    input_feature_dim: ${add:${model.geometry.feature_dim},3} # surface normal as additional input
    dir_encoding_config:
      otype: Identity
      scale: 1.0
      offset: 0.0
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid

system:
  name: metaneusseq-system
  loss:
    lambda_rgb_huber: 10.0
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 0.
    lambda_mask: 0.1
    lambda_eikonal: 0.1
    lambda_sparsity: 0.01
    lambda_distortion: 0.
    lambda_opaque: 0.
    sparsity_scale: 1.
    lambda_sdf_reg: 0

  outer_optimizer:
    name: SGD
    args:
      lr: 1.0

  inner_optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [ 0.9, 0.99 ]
      eps: 1.e-15

  warmup_steps: 100
  warmup_steps_inner: 50
  scheduler:
    name: LinearLR # linear warm-up in the first system.warmup_steps steps
    interval: step
    args:
      start_factor: 1.0 #0.01 #0.0001 -> 0.1
      end_factor: 1.0
      total_iters: ${system.warmup_steps}
#  scheduler:
#    name: SequentialLR
#    interval: step
#    milestones:
#      - ${system.warmup_steps}
#    schedulers:
#      - name: LinearLR # linear warm-up in the first system.warmup_steps steps
#        args:
#          start_factor: 0.01 #0.0001 -> 0.1
#          end_factor: 1.0
#          total_iters: ${system.warmup_steps}
#      - name: ExponentialLR
#        args:
#          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${trainer.max_steps},${system.warmup_steps}}}

checkpoint:
  save_top_k: -1
  every_n_train_steps: 200

export:
  save_mesh: false
  chunk_size: 2097152
  export_vertex_color: True  

trainer:
  max_steps: 3000
  log_every_n_steps: 10
  num_sanity_val_steps: 0
  val_check_interval: 20
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true 
  precision: 32
